### PR TITLE
feat: accept an optional tag type in MessageCall

### PR DESCRIPTION
**Pull request by jqphu**
ethers-rs adds a tag type to their requests if not using legacy feature.
```rust
pub enum TypedTransaction {
    // 0x00
    #[serde(rename = "0x00")]
    Legacy(TransactionRequest),
    // 0x01
    #[serde(rename = "0x01")]
    Eip2930(Eip2930TransactionRequest),
    // 0x02
    #[serde(rename = "0x02")]
    Eip1559(Eip1559TransactionRequest),
}
```

This is also specified in the openethereum docs
https://openethereum.github.io/JSONRPC.html#transactions

This diff adds support to optionally serialize/deserialize this type.

### CODE REVIEW

**Review by vorot93 — CHANGES_REQUESTED** [review]
Very good start. Two comments:
- It's more ergonomic to use [serde_with::DisplayFromStr](https://docs.rs/serde_with/2.0.0/serde_with/struct.DisplayFromStr.html) here
- use `#[serde(rename = "type")]` for tag field

**Comment by jqphu** [comment]
TIL `serde_with::` crate. That's super handy and makes this much nicer :).

Updated based on feedback.

Let me know how you feel about macros :P

**Comment by vorot93** [comment]
Actually, it may be that [SerializeDisplay](https://docs.rs/serde_with/2.0.0/serde_with/derive.SerializeDisplay.html) and [DeserializeFromStr](https://docs.rs/serde_with/2.0.0/serde_with/derive.DeserializeFromStr.html) are the more elegant solution since we control the types.

LGTM otherwise.

**Comment by jqphu** [comment]
Good point. Updated!

**Review by vorot93 — APPROVED** [review]

**Comment by vorot93** [comment]
Thanks for the PR!

**Comment by jqphu** [comment]
Thanks for the reviews (and of course the amazing work on Akula) :)

**Pull request merged**
